# Go cross compiler (xgo): Go 1.12.x
# Copyright (c) 2019 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM e-scavo/xgo2:1.12.13

LABEL MAINTAINER Péter Szilágyi <peterke@gmail.com>
